import type { AxiosAdapter, AxiosResponse, InternalAxiosRequestConfig } from "axios";
// `?url` makes Vite copy the 1.4 MB fixture as a hashed static asset and hand us
// its URL — so it never enters the JS bundle (nor tsc's type inference), and it
// loads once, on demand, only when the demo adapter actually runs.
import dataUrl from "./data.json?url";

/**
 * Static demo adapter — lets the real dashboard run with no backend (e.g. on
 * GitHub Pages). It intercepts every API call and answers from a baked dataset
 * generated by scanning real OSS libraries (server/scripts/gen-demo-fixtures.ts).
 * This module is only imported when VITE_DEMO is set, so the normal build
 * tree-shakes it (and the fixture) away entirely.
 */

type Data = Record<string, any>;

let dataPromise: Promise<Data> | null = null;
const loadData = (): Promise<Data> => (dataPromise ??= fetch(dataUrl).then((r) => r.json()));

const READONLY = "This is a read-only live demo — install QuantumVault to scan your own code.";

function reply(config: InternalAxiosRequestConfig, data: unknown, status = 200): AxiosResponse {
  return {
    data,
    status,
    statusText: status === 200 ? "OK" : "ERROR",
    headers: {},
    config,
  } as AxiosResponse;
}

function blob(config: InternalAxiosRequestConfig, content: string, type: string): AxiosResponse {
  return reply(config, new Blob([content], { type }));
}

function fail(config: InternalAxiosRequestConfig, status: number, message: string): never {
  const err = new Error(message) as Error & { response: AxiosResponse; isAxiosError: boolean };
  err.response = reply(config, { error: message }, status);
  err.isAxiosError = true;
  throw err;
}

function filterAssets(assets: any[], params: any): any[] {
  let out = assets;
  if (params?.family) out = out.filter((a) => a.family === params.family);
  if (params?.priority) out = out.filter((a) => a.risk?.priority === params.priority);
  if (params?.q) {
    const s = String(params.q).toLowerCase();
    out = out.filter(
      (a) =>
        a.file.toLowerCase().includes(s) ||
        a.algorithm.toLowerCase().includes(s) ||
        (a.snippet ?? "").toLowerCase().includes(s),
    );
  }
  return out;
}

// Case-insensitive framework lookup (also makes "FedRAMP" robust).
const findReport = (d: Data, fw: string) =>
  d.reports.find((r: any) => r.framework.toUpperCase() === fw.toUpperCase());

export const demoAdapter: AxiosAdapter = async (config) => {
  const method = (config.method ?? "get").toLowerCase();
  const path = ((config.url ?? "").split("?")[0].replace(/\/+$/, "") || "/").replace(/^(?!\/)/, "/");
  const d = await loadData();

  // Every mutation is disabled in the static demo.
  if (method !== "get") fail(config, 403, READONLY);

  switch (path) {
    case "/dashboard": return reply(config, d.dashboard);
    case "/risk/config": return reply(config, d.riskConfig);
    case "/scans": return reply(config, d.scans);
    case "/monitors": return reply(config, d.monitors);
    case "/compliance": return reply(config, d.reports);
    case "/assets": return reply(config, filterAssets(d.assets, config.params));
    case "/assets/export.csv": {
      // Honor the active family/priority/search filters, exactly like the server.
      const rows = filterAssets(d.assets, config.params).map((a: any) => d.csvRows[a.id]);
      return blob(config, [d.csvHeader, ...rows].join("\r\n") + "\r\n", "text/csv");
    }
    case "/cbom.json": return blob(config, JSON.stringify(d.cbom, null, 2), "application/json");
    case "/sarif.json": return blob(config, JSON.stringify(d.sarif, null, 2), "application/sarif+json");
    case "/assessment/report.json": return reply(config, d.assessment);
    case "/assessment/report.html": return blob(config, d.assessmentHtml, "text/html");
    case "/auth/me": fail(config, 401, "Not authenticated (demo).");
  }

  let m: RegExpMatchArray | null;
  if ((m = path.match(/^\/assets\/([^/]+)$/))) {
    const a = d.assets.find((x: any) => x.id === m![1]);
    return a ? reply(config, a) : fail(config, 404, "asset not found");
  }
  if ((m = path.match(/^\/monitors\/([^/]+)$/))) {
    const det = d.monitorDetail?.[m[1]];
    return det ? reply(config, det) : fail(config, 404, "monitor not found");
  }
  if ((m = path.match(/^\/compliance\/([^/]+)\/export\.json$/))) {
    const r = findReport(d, m[1]);
    return r ? blob(config, JSON.stringify(r, null, 2), "application/json") : fail(config, 404, "report not found");
  }
  if ((m = path.match(/^\/compliance\/([^/]+)\/export\.html$/))) {
    const r = findReport(d, m[1]);
    const html = r ? d.complianceHtml?.[r.framework] : undefined;
    // openCompliancePdf() requests this as text.
    return html ? reply(config, html) : fail(config, 404, "report not found");
  }
  if ((m = path.match(/^\/compliance\/([^/]+)$/))) {
    const r = findReport(d, m[1]);
    return r ? reply(config, r) : fail(config, 404, "report not found");
  }

  return fail(config, 404, `demo: no fixture for ${path}`);
};
